python_library(
  name='lib',
  dependencies=[
    '3rdparty/python:flask',
    '3rdparty/python:flask-login',
    '3rdparty/python:flask-appbuilder',
  ],
  provides=setup_py(
    name='example_api',
    version='0.1.0',
    description='A small flask app',
    long_description='''It is a really small flask app''',
    url='https://github.com/jdmeyer3/minimal-python-api',
    license='Apache License, Version 2.0',
    zip_safe=True,
    classifiers=[
      'Intended Audience :: Developers',
      'License :: OSI Approved :: Apache Software License',
      'Operating System :: MacOS :: MacOS X',
      'Operating System :: POSIX :: Linux',
      'Programming Language :: Python',
      'Topic :: Software Development :: Build Tools',
      'Topic :: Software Development :: Testing',
    ]
  )
)
